### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'NoneType' error during  step 2-B) Transform time-dependent data

### ISSUE THREAD

**Issue by ManuTel** [shengpu1126/FIDDLE#10]
I was trying out the demo of FIDDLE using Google Colab (http://tiny.cc/get_FIDDLE)  as well as locally.  While running the preprocessing step using the provided data I encountered following error. I apologise for such small information as this is being my first public issue.

**Comment by shengpu-tang** [comment]
Hello, apologies for the delayed response. I have just fixed the Google Colab demo so it should work fine now.

**Comment by ManuTel** [comment]
It's working now. Thanks!
