### ISSUE TITLE
Questions about the functions make_float and is_numeric in helpers.py

### ISSUE THREAD

**Issue by stdoo** [shengpu1126/FIDDLE#2]
Hi, the functions make_float and is_numeric can't catch NoneType error. You can reproduce this error by running the Run.ipynb. Besides, the **Example Usage** in README.md is not runable, clearly the test in path should be tests.

**Comment by shengpu-tang** [comment]
Thank you for bringing this to my attention. I'm working on fixing the bugs soon.
